# Generated by Django 3.2.4 on 2024-07-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_personalinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personalinformation',
        ),
    ]
